#!/usr/bin/env python3
"""Generate compile_commands.json and .clangd for clangd / Cursor."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path


def gcc_include_dir(cc: str) -> str:
    return subprocess.check_output([cc, "-print-file-name=include"], text=True).strip()


def collect_sources(root: Path) -> list[Path]:
    src_dir = root / "app" / "src"
    if not src_dir.is_dir():
        print(f"warning: no sources under {src_dir}", file=sys.stderr)
        return []
    return sorted(src_dir.glob("*.c"))


def main() -> int:
    root = Path(os.environ.get("PROJECT_ROOT", Path.cwd())).resolve()
    cc = os.environ.get("CC", "arm-none-eabi-gcc")
    opencm3 = os.environ.get("OPENCM3_DIR", "libopencm3")

    gcc_inc = gcc_include_dir(cc)
    opencm3_inc = (root / opencm3 / "include").resolve()

    defines = ["STM32F4", "STM32F401RET6"]
    cpu_flags = [
        "-mcpu=cortex-m4",
        "-mthumb",
        "-mfloat-abi=hard",
        "-mfpu=fpv4-sp-d16",
    ]
    base_flags = [
        "--target=arm-none-eabi",
        "-Os",
        "-Wall",
        "-Wextra",
        "-ggdb3",
        *[f"-D{d}" for d in defines],
        f"-I{opencm3_inc}",
        "-isystem",
        gcc_inc,
        *cpu_flags,
    ]

    entries = []
    for src in collect_sources(root):
        rel = src.relative_to(root)
        entries.append(
            {
                "directory": str(root),
                "arguments": ["clang", *base_flags, "-c", str(rel), "-o", "firmware.o"],
                "file": str(rel),
            }
        )

    compile_db = root / "compile_commands.json"
    compile_db.write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")

    clangd = f"""# Generated by: make compile_db
CompileFlags:
  Add:
    - --target=arm-none-eabi
    - -mcpu=cortex-m4
    - -mthumb
    - -mfloat-abi=hard
    - -mfpu=fpv4-sp-d16
    - -DSTM32F4
    - -DSTM32F401RET6
    - -I{opencm3_inc}
    - -isystem
    - {gcc_inc}
"""
    (root / ".clangd").write_text(clangd, encoding="utf-8")

    print(f"Wrote {compile_db.name} ({len(entries)} translation units)")
    print(f"Wrote .clangd (GCC includes: {gcc_inc})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
